version: '3'

services:
    exchange_crypto_web:
        build:
            context: .
        container_name: exchange_crypto_web
        ports:
            - "18000:80"
        volumes:
            - .:/var/www/html
        networks:
            exchange-crypto-network:
                aliases:
                    - exchange_crypto_web
    exchange_crypto_mysql:
        platform: linux/x86_64
        container_name: exchange_crypto_mysql
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
        ports:
            - "18001:3306"
#        volumes:
#            - ./storage/data:/var/lib/mysql
        networks:
            exchange-crypto-network:
                aliases:
                    - exchange_crypto_mysql
networks:
    exchange-crypto-network:
        external:
            name: exchange-crypto-network
